# Site settings
  # Note: after inputting your content, you may need to stop and restart jekyll server for changes to take effect.
  # When filling this file in, below, be sure to DELETE the "#" comments - example, greeting should look like - greeting: Hello, I'm Simpol.

#content for nav.html
title: Yuan-Syun Ye
subtitle: 葉元勲畢業於國立交通大學多媒體工程研究所，碩士論文研究領域為人機互動(Human Computer Interface, HCI)、虛擬實境(Virtual Reality, VR)。擅長工具為Unity 3D，以及能透過Arudino與3D Printer快速進行硬體裝置的開發。目前正在尋找與虛擬實境、擴增實境以及物聯網相關的工作機會。

#content for index.html
  #Add your own info, deleting the comments "#". This data automatically writes to the Index page's mini, about section.
greeting: #GREETING_GOES_HERE | default: Hello, I'm Simpol.
logo_img: #LOGO_IMG_SRC_GOES_HERE | default: /assets/img/simpol-theme-square-writing-logo.png
subgreeting_one: #SUBGREETING_ONE_GOES_HERE
subgreeting_two: #SUBGREETING_TWO_GOES_HERE

# Again: after inputting your content, you may need to stop and restart jekyll server for changes to take effect.

#content for nav.html (shown on desktop) navigation links
nav_link_one_name: github
nav_link_one_link: "https://github.com/yuansyun"

nav_link_two_name: facebook
nav_link_two_link: "https://www.facebook.com/YuanSyun/"

nav_link_three_name: twitter
nav_link_three_link: "https://twitter.com/yuansyun"

#content for footer.html (shown on mobile) footer navigation links
footer_link_one_name: github
footer_link_one_link: "https://github.com/yuansyun"

footer_link_two_name: facebook
footer_link_two_link: "https://www.facebook.com/YuanSyun/"

footer_link_three_name: twitter
footer_link_three_link: "https://twitter.com/yuansyun"

baseurl: "https://yuansyun.github.io/" 
google_tracking_id: #deletme-Google Analytics Tracking ID- UA-XXXXXXXX-X
copyright_name: Mathson Design, LLC

# SEO data (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/img/simpol-favicon.png
description: Simpol Theme is a clean, minimal website theme all about the writing, the content. Currently available for Jekyll. Perfect for blogging.
author:
  name: Yuan-Syun Ye
  email: yuansyuntw@gmail.com
  twitter: yuansyun

social:
  name: Yuan-Syun Ye
  links:
    - https://twitter.com/yuansyun
    - https://github.com/yuansyun

# Build settings
permalink: pretty
paginate: 12

defaults:
  -
    scope:
      path: "assets/img"
    values:
      image: true

plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- vendor
